CREATE TABLE `authOs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`name_id` BIGINT UNSIGNED NOT NULL,`ver_id` BIGINT UNSIGNED NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `uq_os` (`name_id`,`ver_id`)
);