CREATE TABLE `authSignInLog` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`uid` BIGINT UNSIGNED NOT NULL,`ip` VARBINARY(16) NOT NULL,`device_id` BIGINT UNSIGNED NOT NULL,`browser_id` BIGINT UNSIGNED NOT NULL,`os_id` BIGINT UNSIGNED NOT NULL,`timezone` TINYINT NOT NULL,`ts` BIGINT UNSIGNED NOT NULL DEFAULT (unix_timestamp()),PRIMARY KEY (`id`)
);