[package]
name = "captcha_"
version = "0.1.1"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/i18n-site/mod.git"
homepage = "https://github.com/i18n-site/mod/tree/dev/mod/captcha_"
description = "captcha"
keywords = ["hpc", "mod"]

[dependencies]
aok = "0.1.18"
click_captcha = { version = "0.1.38", features = [
  "ico_li",
  "make",
  "verify",
  "webp",
] }
ih = "0.1.15"
pb-jelly = "0.0.17"
pc = "0.1.13"
rand = "0.10.0"
s_ = "0.1.6"
ub64 = "0.1.14"
xbin = "0.1.9"
xboot = "0.1.35"
xerr = "0.1.16"
xkv = { version = "0.1.51", features = ["r"] }

[dev-dependencies]
loginit = "0.1.18"
static_init = "1.0.4"
tokio = { version = "1.50.0", features = [
  "macros",
  "rt",
  "rt-multi-thread",
  "time",
  "fs",
  "io-util",
] }

[package.metadata.docs.rs]
all-features = true
